import { jsPDF } from 'jspdf';
import type { Meeting } from '../types';

export interface PdfContent {
  title: string;
  date: string;
  attendees: string[];
  overview: string;
  decisions: string[];
  actionItems: string[];
  topics: string[];
}

export function buildPdfContent(meeting: Meeting): PdfContent {
  return {
    title: meeting.title,
    date: new Date(meeting.createdAt).toLocaleDateString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC',
    }),
    attendees: meeting.attendees,
    overview: meeting.summary?.overview ?? '',
    decisions: meeting.summary?.decisions ?? [],
    actionItems: meeting.summary?.actionItems ?? [],
    topics: meeting.summary?.topics ?? [],
  };
}

export function exportMeetingPdf(meeting: Meeting): void {
  const content = buildPdfContent(meeting);
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });

  const margin = 60;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addText = (text: string, size: number, bold: boolean, color: [number, number, number]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * size * 1.4;
  };

  const addSection = (label: string, items: string[]) => {
    if (!items.length) return;
    y += 10;
    addText(label.toUpperCase(), 9, true, [80, 80, 80]);
    y += 2;
    items.forEach((item) => addText(`• ${item}`, 11, false, [60, 60, 60]));
  };

  // Header
  addText(content.title, 18, true, [20, 20, 20]);
  y += 2;
  addText(content.date, 10, false, [120, 120, 120]);
  if (content.attendees.length) {
    addText(`Attendees: ${content.attendees.join(', ')}`, 10, false, [120, 120, 120]);
  }
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;

  // Overview
  if (content.overview) {
    addText('OVERVIEW', 9, true, [80, 80, 80]);
    y += 2;
    addText(content.overview, 11, false, [60, 60, 60]);
  }

  addSection('Decisions', content.decisions);
  addSection('Action Items', content.actionItems);
  addSection('Topics', content.topics);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text('Generated by Notes App', pageWidth / 2, pageHeight - 30, { align: 'center' });

  const slug = content.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  doc.save(`${slug}-${new Date(meeting.createdAt).toISOString().slice(0, 10)}.pdf`);
}
